apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia-v1
  labels:
    app: kubiarc
spec:
  replicas: 2
  template:
    metadata:
      name: kubiamain
      labels: 
        app: kubia
    spec:
      containers:
      - name: webserver
        image: luksa/kubia:v1
  selector:
      app: kubia