apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: curl
  name: curl
spec:
  containers:
  - image: tutum/curl
    name: curl
    command: ["sleep", "99999"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
