apiVersion: v1
kind: Pod
metadata:
  name: downwardvolume
  labels:
    app: test
  annotations:
    env: dev
    list: |
      name
      ip
      labels
      annotations
spec:
  containers:
  - name: main
    image: busybox
    command: ["sleep", "999999"]
    volumeMounts:
      - mountPath: /etc/downward
        name: downward
  volumes:
  - name: downward
    downwardAPI:
      items:
      - path: "podName"
        fieldRef:
          fieldPath: metadata.name
      - path: "podNamespace"
        fieldRef:
          fieldPath: metadata.namespace
      - path: "labels"
        fieldRef:
          fieldPath: metadata.labels
      - path: "annotations"
        fieldRef:
          fieldPath: metadata.annotations
