apiVersion: v1
kind: Pod
metadata:
    name: fortune-https
    labels:
        app: fortune-https
spec:
    containers:
    -  name: fortune-html
       image: visw2290/fortune:env
       env:
       - name: INTERVAL
         valueFrom:
             configMapKeyRef:
                 name: fortune-config
                 key: sleep-interval
       volumeMounts:
       -  mountPath: /var/htdocs
          name: html
    -  name: web-server
       image: nginx:alpine
       ports:
       -  containerPort: 80
          protocol: TCP
       volumeMounts:
       -  name: html
          mountPath: /usr/share/nginx/html
          readOnly: true
       -  name: config
          mountPath: /etc/nginx/conf.d
          readOnly: true
       - name: certs
         mountPath: /etc/nginx/certs
         readOnly: true
    volumes:
    -  name: html
       emptyDir: {}
    -  name: config
       configMap:
           name: fortune-config
           items:
           -  key: my-nginx-conf.conf
              path: ssl.conf
    -  name: certs
       secret:
           secretName: fortune-https